- hosts: all
  become: true
  tasks:
    - name: update and upgrade apt
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: install nvim
      community.general.snap:
        classic: true
        name:
          - nvim

- hosts: all
  become: true
  roles:
    - role: "./roles/golang"
    - role: "./roles/free5gc"
