- name: clone free5gc repo
  ansible.builtin.git:
    repo: "{{ free5gc_repo_url }}"
    version: "{{ free5gc_repo_branch }}"
    dest: "{{ free5gc_clone_path }}"
    recursive: true
  become_user: vagrant

