- name: Install microk8s
  community.general.snap:
    classic: true
    name:
      - microk8s

- name: add user to group `microk8s`
  ansible.builtin.user:
    name: vagrant
    append: true
    groups:
      - microk8s

